# Travis CI configuration for the serial-core PHP library.
#
# <http://travis-ci.org>
#
language: php
php:
    #- 5.2
    - 5.3
    - 5.4

branches:
    only:
        - master
        - dev

# Run the test suite against the source tree and create a phar distribution.
# The phar file will automatically be verified against the test suite.
script: php -f setup.php test phar 
