# Travis CI configuration for the serial-core PHP library.
#
# <http://travis-ci.org>
#
language: php
php:
    - 5.2
    - 5.3
    - 5.4
    - 5.5

branches:
    only:
        - master
        - dev

# Run the test suite against the source tree and create a phar distribution.
# The phar file will automatically be verified against the test suite.

before_script: pecl install phar
script: php -f setup.php test phar 
