## Travis CI configuration for the serial-core library.
##
##  <https://travis-ci.org/mdklatt/serial-php>
##
language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

branches:
  only:
    - master
    - dev

sudo: false

before_script:
  - composer install
    
script:
  # Run the test suite and verify that a phar archive can be built.
  - vendor/bin/phing test 
  - vendor/bin/phing phar
  